global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'tawfiqsani54@gmail.com'
    from: 'tawfiqsani54@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'tawfiqsani54@gmail.com'
    auth_identity: 'tawfiqsani54@gmail.com'
    auth_password: '*******' 
